//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Pizza.Models.DATA
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PizzaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PizzaEntities object using the connection string found in the 'PizzaEntities' section of the application configuration file.
        /// </summary>
        public PizzaEntities() : base("name=PizzaEntities", "PizzaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PizzaEntities object.
        /// </summary>
        public PizzaEntities(string connectionString) : base(connectionString, "PizzaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PizzaEntities object.
        /// </summary>
        public PizzaEntities(EntityConnection connection) : base(connection, "PizzaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Discount> Discounts
        {
            get
            {
                if ((_Discounts == null))
                {
                    _Discounts = base.CreateObjectSet<Discount>("Discounts");
                }
                return _Discounts;
            }
        }
        private ObjectSet<Discount> _Discounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Discounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDiscounts(Discount discount)
        {
            base.AddObject("Discounts", discount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PizzaModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="custormer_UID">Initial value of the Custormer_UID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        /// <param name="originalAddDate">Initial value of the OriginalAddDate property.</param>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        public static Customer CreateCustomer(global::System.Int32 custormer_UID, global::System.String name, global::System.String phoneNumber, global::System.DateTime originalAddDate, global::System.Int32 employeeID)
        {
            Customer customer = new Customer();
            customer.Custormer_UID = custormer_UID;
            customer.Name = name;
            customer.PhoneNumber = phoneNumber;
            customer.OriginalAddDate = originalAddDate;
            customer.EmployeeID = employeeID;
            return customer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Custormer_UID
        {
            get
            {
                return _Custormer_UID;
            }
            set
            {
                if (_Custormer_UID != value)
                {
                    OnCustormer_UIDChanging(value);
                    ReportPropertyChanging("Custormer_UID");
                    _Custormer_UID = StructuralObject.SetValidValue(value, "Custormer_UID");
                    ReportPropertyChanged("Custormer_UID");
                    OnCustormer_UIDChanged();
                }
            }
        }
        private global::System.Int32 _Custormer_UID;
        partial void OnCustormer_UIDChanging(global::System.Int32 value);
        partial void OnCustormer_UIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false, "PhoneNumber");
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true, "Address1");
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true, "Address2");
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true, "State");
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true, "Zip");
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OriginalAddDate
        {
            get
            {
                return _OriginalAddDate;
            }
            set
            {
                OnOriginalAddDateChanging(value);
                ReportPropertyChanging("OriginalAddDate");
                _OriginalAddDate = StructuralObject.SetValidValue(value, "OriginalAddDate");
                ReportPropertyChanged("OriginalAddDate");
                OnOriginalAddDateChanged();
            }
        }
        private global::System.DateTime _OriginalAddDate;
        partial void OnOriginalAddDateChanging(global::System.DateTime value);
        partial void OnOriginalAddDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value, "EmployeeID");
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PizzaModel", Name="Discount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Discount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Discount object.
        /// </summary>
        /// <param name="discountID">Initial value of the DiscountID property.</param>
        /// <param name="discountCode">Initial value of the DiscountCode property.</param>
        /// <param name="discountPercent">Initial value of the DiscountPercent property.</param>
        public static Discount CreateDiscount(global::System.Int32 discountID, global::System.String discountCode, global::System.Decimal discountPercent)
        {
            Discount discount = new Discount();
            discount.DiscountID = discountID;
            discount.DiscountCode = discountCode;
            discount.DiscountPercent = discountPercent;
            return discount;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DiscountID
        {
            get
            {
                return _DiscountID;
            }
            set
            {
                if (_DiscountID != value)
                {
                    OnDiscountIDChanging(value);
                    ReportPropertyChanging("DiscountID");
                    _DiscountID = StructuralObject.SetValidValue(value, "DiscountID");
                    ReportPropertyChanged("DiscountID");
                    OnDiscountIDChanged();
                }
            }
        }
        private global::System.Int32 _DiscountID;
        partial void OnDiscountIDChanging(global::System.Int32 value);
        partial void OnDiscountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DiscountCode
        {
            get
            {
                return _DiscountCode;
            }
            set
            {
                OnDiscountCodeChanging(value);
                ReportPropertyChanging("DiscountCode");
                _DiscountCode = StructuralObject.SetValidValue(value, false, "DiscountCode");
                ReportPropertyChanged("DiscountCode");
                OnDiscountCodeChanged();
            }
        }
        private global::System.String _DiscountCode;
        partial void OnDiscountCodeChanging(global::System.String value);
        partial void OnDiscountCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiscountDescription
        {
            get
            {
                return _DiscountDescription;
            }
            set
            {
                OnDiscountDescriptionChanging(value);
                ReportPropertyChanging("DiscountDescription");
                _DiscountDescription = StructuralObject.SetValidValue(value, true, "DiscountDescription");
                ReportPropertyChanged("DiscountDescription");
                OnDiscountDescriptionChanged();
            }
        }
        private global::System.String _DiscountDescription;
        partial void OnDiscountDescriptionChanging(global::System.String value);
        partial void OnDiscountDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DiscountPercent
        {
            get
            {
                return _DiscountPercent;
            }
            set
            {
                OnDiscountPercentChanging(value);
                ReportPropertyChanging("DiscountPercent");
                _DiscountPercent = StructuralObject.SetValidValue(value, "DiscountPercent");
                ReportPropertyChanged("DiscountPercent");
                OnDiscountPercentChanged();
            }
        }
        private global::System.Decimal _DiscountPercent;
        partial void OnDiscountPercentChanging(global::System.Decimal value);
        partial void OnDiscountPercentChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PizzaModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employee_UID">Initial value of the Employee_UID property.</param>
        /// <param name="employeeName">Initial value of the EmployeeName property.</param>
        /// <param name="employeeUsername">Initial value of the EmployeeUsername property.</param>
        /// <param name="isDriver">Initial value of the IsDriver property.</param>
        public static Employee CreateEmployee(global::System.Int32 employee_UID, global::System.String employeeName, global::System.String employeeUsername, global::System.Boolean isDriver)
        {
            Employee employee = new Employee();
            employee.Employee_UID = employee_UID;
            employee.EmployeeName = employeeName;
            employee.EmployeeUsername = employeeUsername;
            employee.IsDriver = isDriver;
            return employee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Employee_UID
        {
            get
            {
                return _Employee_UID;
            }
            set
            {
                if (_Employee_UID != value)
                {
                    OnEmployee_UIDChanging(value);
                    ReportPropertyChanging("Employee_UID");
                    _Employee_UID = StructuralObject.SetValidValue(value, "Employee_UID");
                    ReportPropertyChanged("Employee_UID");
                    OnEmployee_UIDChanged();
                }
            }
        }
        private global::System.Int32 _Employee_UID;
        partial void OnEmployee_UIDChanging(global::System.Int32 value);
        partial void OnEmployee_UIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmployeeName
        {
            get
            {
                return _EmployeeName;
            }
            set
            {
                OnEmployeeNameChanging(value);
                ReportPropertyChanging("EmployeeName");
                _EmployeeName = StructuralObject.SetValidValue(value, false, "EmployeeName");
                ReportPropertyChanged("EmployeeName");
                OnEmployeeNameChanged();
            }
        }
        private global::System.String _EmployeeName;
        partial void OnEmployeeNameChanging(global::System.String value);
        partial void OnEmployeeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmployeeUsername
        {
            get
            {
                return _EmployeeUsername;
            }
            set
            {
                OnEmployeeUsernameChanging(value);
                ReportPropertyChanging("EmployeeUsername");
                _EmployeeUsername = StructuralObject.SetValidValue(value, false, "EmployeeUsername");
                ReportPropertyChanged("EmployeeUsername");
                OnEmployeeUsernameChanged();
            }
        }
        private global::System.String _EmployeeUsername;
        partial void OnEmployeeUsernameChanging(global::System.String value);
        partial void OnEmployeeUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDriver
        {
            get
            {
                return _IsDriver;
            }
            set
            {
                OnIsDriverChanging(value);
                ReportPropertyChanging("IsDriver");
                _IsDriver = StructuralObject.SetValidValue(value, "IsDriver");
                ReportPropertyChanged("IsDriver");
                OnIsDriverChanged();
            }
        }
        private global::System.Boolean _IsDriver;
        partial void OnIsDriverChanging(global::System.Boolean value);
        partial void OnIsDriverChanged();

        #endregion

    }

    #endregion

}
